project_id = "rbmsbppvpgcrmtkdfahy"

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/signup", "http://127.0.0.1:3000/reset-password", "http://localhost:3000/signup", "http://localhost:3000/reset-password"]

[auth.email]
enable_signup = true
enable_confirmations = false