// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
import type { Database as DB, Json as JsonType } from './database.types';

export type Database = DB;
export type Json = JsonType;

// Re-export commonly used types for convenience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];

// Project reference: nrlzptrtukdeaugphayd
// Last updated: 2026-04-16T05:01:09.193201

// ─── Named row type aliases ────────────────────────────────────────────────────
// Convenience aliases for the most-used HRMS tables. Import these instead of
// the verbose `Tables<'...'>`  form in service packages.

export type AnnouncementRow        = Tables<'announcements'>;
export type AppraisalRow           = Tables<'appraisals'>;
export type AppraisalItemRow       = Tables<'appraisal_items'>;
export type ApprovalDecisionRow    = Tables<'approval_decisions'>;
export type ApprovalInstanceRow    = Tables<'approval_instances'>;
export type ApprovalStepRow        = Tables<'approval_steps'>;
export type AttendanceRecordRow    = Tables<'attendance_records'>;
export type EmployeeRow            = Tables<'employees'>;
export type LeaveBalanceRow        = Tables<'leave_balances'>;
export type LeaveRequestRow        = Tables<'leave_requests'>;
export type LeaveTypeRow           = Tables<'leave_types'>;
export type PayrollItemRow         = Tables<'payroll_items'>;
export type PayrollRunRow          = Tables<'payroll_runs'>;
export type ProfileRow             = Tables<'profiles'>;
