export {
  HRMS_ACCESS_ROLES,
  HRMS_ADMIN_ROLES,
  HRMS_APPRAISAL_PARTICIPANT_ROLES,
  HRMS_APPROVAL_INBOX_ROLES,
  HRMS_LEAVE_APPROVER_ROLES,
  HRMS_MANAGER_ROLES,
  HRMS_PAYROLL_ROLES,
  HRMS_SELF_SERVICE_ROLES,
  PII_VIEW_ROLES,
} from '@flc/auth';
